name: untitled
description:
publish_to:
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  firebase_core: ^3.13.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.2
  local_auth: ^2.3.0
  image_picker: ^1.1.2
  audioplayers: ^5.2.1
  firebase_storage: ^12.4.6
  google_mlkit_face_detection: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/welcome_images/welcome.jpg
    - assets/login_image/login.png
    - assets/audio/success.mp3
    - assets/audio/failure.mp3
